version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: Iyed/crypto_assets_api:1.0.0
    restart: unless-stopped
    ports:
      - "8080:80"  # host_port:container_port
    environment:
      - ENV=production
    
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"