replicaCount: 2
image:
  repository: ghcr.io/ubuntu-devops/crypto-api
  tag: ""
  pullPolicy: IfNotPresent

service:
  port: 80
  targetPort: 8000
ingress:
  enabled: false
ressources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi