name: CI/CD - Crypto Assets API

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: ${{ secrets.GCP_REGION }}
  APP_NAME: ${{ secrets.GCP_APP_NAME }}
  REPO_NAME: ${{ secrets.GCP_REPO_NAME }} 

jobs:
  build-and-doply:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write
      actions: read

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

    # Install gcloud CLI
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

    # Verify gcloud authentication
      - name: Verify gcloud authentication
        run: |
          gcloud auth list

    # Verify Artifact Registry access

      - name: Verify Artifact Registry access
        run: gcloud artifacts repositories list --location=${{ secrets.GCP_REGION }}

      - name: Configure Docker auth for Artifact Registry
        run: gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev --quiet


    # Build Docker image 
      - name: Build docker image
        run: |
          IMAGE="${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_REPO_NAME }}/${{ secrets.GCP_APP_NAME }}:${{ github.sha }}"
          docker build -t $IMAGE .
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

    # Push Docker image to Artifact Registry
      - name: Push Docker image to Artifact Registry
        run: docker push ${{ env.IMAGE }}

    # Deploy to Cloud Run
      - name: Deploy the image
        run: |
          gcloud run deploy Assets-${{ env.APP_NAME }} \
            --image ${{ env.IMAGE }} \
            --region ${{ secrets.GCP_REGION }} \
            --platform managed \
            --allow-unauthenticated
