# name: CI
# on: [push, pull_request]
# jobs:
#   lint-test:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - uses: actions/setup-python@v5
#         with: { python-version: '3.12' }
#       - run: pip install ruff pytest
#       - run: ruff check app
#       - run: pytest app
#   build:
#     needs: lint-test
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - uses: actions/setup-buildx-action@v3
#       - uses: docker/login-action@v3
#         with:
#           registry: ghcr.io
#           username: ${{ github.actor }}
#           password: ${{ secrets.GITHUB_TOKEN }}
      
#       - uses: docker/build-push-action@v5
#         with:
#           context: .
#           push: true
#           tags: ghcr.io/${{ github.repository }}:${{ github.sha }}
        