name: Deploy FastAPI + n8n

on: 
  push:
    branches:
      - Development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: change the Scripts permission
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
          chmod +x ./start.sh ./n8n/deploy-n8n.sh

      - name: Execute Deployment Scripts
        run: bash ./n8n/deploy-n8n.sh && bash ./start.sh
        working-directory: ${{ github.workspace }}